### ISSUE TITLE
Debian package does not start up on desktop application launch

### ISSUE THREAD

**Issue by mdhishaamakhtar** [GDGVIT/HandWriter#5]

**Comment by Geek-ubaid** [comment]
Specify details like put up screenshots of errors, the method followed etc. @mdhishaamakhtar

**Comment by mdhishaamakhtar** [comment]
There is no error. It just does not launch on pressing the desktop icon.

**Comment by SaurusXI** [comment]
@L04DB4L4NC3R and I are looking into it

**Comment by mdhishaamakhtar** [comment]
Also the package made my system crash and made it get locks errors.

**Comment by SaurusXI** [comment]
@mdhishaamakhtar Please post screenshots of the locks errors, just to make sure that the errors originate from the package. To my knowledge, that should not be possible for the package to do since it would require superuser access. If it is a problem with the package, will remove the debian link from Installation.md until this is fixed.

**Comment by SaurusXI** [comment]
![HandWriter_bug](https://user-images.githubusercontent.com/39787073/79380919-c2db9a00-7f7e-11ea-85cf-234c1fd4f20e.png)
Replicated the installation on an Ubuntu VM. The problem seems to be that FBS uses an Ubuntu 16.04 docker image (because applications built here are usually portable to 18.04 but not the other way around); however since 17.10 ZLIB-1.2.9 .so file symlinks were broken for many applications built on older systems so this is an old known bug. To fix this, I'll add a symlink in installation steps in Installation.md 
As for @mdhishaamakhtar system locks errors, those seem to be unrelated to the application. Perhaps just a package manager database lock. Anyway, thanks for bringing this to my attention.
Making a PR with updated installation instructions.
